"""create support_settings table

Revision ID: 2103f59e79c6
Revises: 1eac1b424818
Create Date: 2025-12-03 19:04:31.526082

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2103f59e79c6'
down_revision: Union[str, Sequence[str], None] = '1eac1b424818'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    """Upgrade schema: create support_settings table."""
    op.create_table(
        "support_settings",
        sa.Column("id", sa.Integer, primary_key=True),
        sa.Column("outlet_id", sa.Integer, nullable=False),
        sa.Column("web_url", sa.String(255), nullable=False),
        sa.Column("settings", sa.JSON, nullable=True),
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('apscheduler_jobs',
    sa.Column('id', sa.VARCHAR(length=191), autoincrement=False, nullable=False),
    sa.Column('next_run_time', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('job_state', postgresql.BYTEA(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('apscheduler_jobs_pkey'))
    )
    op.create_index(op.f('ix_apscheduler_jobs_next_run_time'), 'apscheduler_jobs', ['next_run_time'], unique=False)
    # ### end Alembic commands ###
