"""updated agent table -add category, subcategory, created_at, updated_at

Revision ID: 5c3100b117ea
Revises: 5f4ddfda3ebb
Create Date: 2026-01-28 16:32:39.633652

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5c3100b117ea'
down_revision: Union[str, Sequence[str], None] = '5f4ddfda3ebb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_apscheduler_jobs_next_run_time'), table_name='apscheduler_jobs')
    op.drop_table('apscheduler_jobs')
    op.add_column('agents', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('agents', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.alter_column('agents', 'skills',
               existing_type=postgresql.ARRAY(sa.TEXT()),
               server_default=None,
               type_=postgresql.ARRAY(sa.String()),
               existing_nullable=False)
    op.alter_column('agents', 'category',
               existing_type=postgresql.ENUM('general', 'billing', 'technical', 'product', 'shipping', 'escalation', name='category_enum'),
               nullable=False)
    op.alter_column('agents', 'sub_category',
               existing_type=postgresql.ENUM('invoice', 'refund', 'payment', 'login', 'bug', 'feature', 'delivery', 'delay', 'urgent', name='sub_category_enum'),
               nullable=False)
    op.drop_index(op.f('idx_agents_category_sub_category'), table_name='agents')
    op.create_index(op.f('ix_agents_created_at'), 'agents', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_agents_created_at'), table_name='agents')
    op.create_index(op.f('idx_agents_category_sub_category'), 'agents', ['category', 'sub_category'], unique=False)
    op.alter_column('agents', 'sub_category',
               existing_type=postgresql.ENUM('invoice', 'refund', 'payment', 'login', 'bug', 'feature', 'delivery', 'delay', 'urgent', name='sub_category_enum'),
               nullable=True)
    op.alter_column('agents', 'category',
               existing_type=postgresql.ENUM('general', 'billing', 'technical', 'product', 'shipping', 'escalation', name='category_enum'),
               nullable=True)
    op.alter_column('agents', 'skills',
               existing_type=postgresql.ARRAY(sa.String()),
               server_default=sa.text('ARRAY[]::text[]'),
               type_=postgresql.ARRAY(sa.TEXT()),
               existing_nullable=False)
    op.drop_column('agents', 'updated_at')
    op.drop_column('agents', 'created_at')
    op.create_table('apscheduler_jobs',
    sa.Column('id', sa.VARCHAR(length=191), autoincrement=False, nullable=False),
    sa.Column('next_run_time', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('job_state', postgresql.BYTEA(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('apscheduler_jobs_pkey'))
    )
    op.create_index(op.f('ix_apscheduler_jobs_next_run_time'), 'apscheduler_jobs', ['next_run_time'], unique=False)
    # ### end Alembic commands ###
