"""create support_settings table

Revision ID: 8b133ec355d5
Revises: 2103f59e79c6
Create Date: 2025-12-03 19:05:47.979666

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b133ec355d5'
down_revision: Union[str, Sequence[str], None] = '2103f59e79c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None



def upgrade() -> None:
    """Upgrade schema: create support_settings table."""
    op.create_table(
        "support_settings",
        sa.Column("id", sa.Integer, primary_key=True),
        sa.Column("outlet_id", sa.Integer, nullable=False),
        sa.Column("web_url", sa.String(255), nullable=False),
        sa.Column("settings", sa.JSON, nullable=True),
    )

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
